fix betterleaks pre commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -3,4 +3,9 @@
 #
 # SPDX-License-Identifier: MIT
 
+if ! command -v changeset >/dev/null 2>&1; then
+  echo "🛑 HALT: 'betterleaks' command not found in your PATH!"
+  exit 1
+fi
+
 betterleaks protect --staged
